name 'stress'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures stress'
long_description 'Installs/Configures stress'
version '0.1.0'

depends 'apt'
depends 'build-essential'
depends 'yum-centos'
depends 'yum-chef'
depends 'chocolatey'
